services:
  ss14-server:
    image: ghcr.io/dkgitdev/SS14-Docker-Linux-Server:main
    ports:
      - "1212:1212/tcp"
      - "1212:1212/udp"
      - "5000:5000/tcp"
      - "5000:5000/udp"
    volumes:
      - ss14vol:/ss14
    restart: always
volumes:
  ss14vol:
